CREATE TABLE ai_query_examples (
    id            BIGSERIAL PRIMARY KEY,
    question_text VARCHAR(500) NOT NULL,
    intent        VARCHAR(50) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_ai_query_examples_intent ON ai_query_examples(intent);

-- Seed training data for the intent classifier. PRODUCT_SEARCH = general catalog
-- browsing; LOW_STOCK_SEARCH = urgency/reorder-flavored questions. More examples can
-- be added later via POST /api/ai/query-examples so the classifier keeps learning.
INSERT INTO ai_query_examples (question_text, intent) VALUES
('show me all products', 'PRODUCT_SEARCH'),
('list all cement products', 'PRODUCT_SEARCH'),
('find products in the cement category', 'PRODUCT_SEARCH'),
('show me products from Dangote', 'PRODUCT_SEARCH'),
('what products do we have in the paint category', 'PRODUCT_SEARCH'),
('search for pipes', 'PRODUCT_SEARCH'),
('show all brands of cement', 'PRODUCT_SEARCH'),
('list products by Dangote brand', 'PRODUCT_SEARCH'),
('find all steel products', 'PRODUCT_SEARCH'),
('show me the product catalog', 'PRODUCT_SEARCH'),
('what cement products are available', 'PRODUCT_SEARCH'),
('list products in the roofing category', 'PRODUCT_SEARCH'),
('search for products named nail', 'PRODUCT_SEARCH'),
('show me all Dangote products', 'PRODUCT_SEARCH'),
('find products in the plumbing category', 'PRODUCT_SEARCH'),
('what brands do we sell', 'PRODUCT_SEARCH'),
('show me all paint products', 'PRODUCT_SEARCH'),
('list every product we carry', 'PRODUCT_SEARCH'),
('search products by tiles', 'PRODUCT_SEARCH'),
('find products with steel in the name', 'PRODUCT_SEARCH'),
('show me the full product list', 'PRODUCT_SEARCH'),
('list all items in the electrical category', 'PRODUCT_SEARCH'),
('what products come from BUA', 'PRODUCT_SEARCH'),
('search for products called pipe', 'PRODUCT_SEARCH'),
('show me products in the hardware category', 'PRODUCT_SEARCH'),
('find all wood products', 'PRODUCT_SEARCH'),
('list products from the timber category', 'PRODUCT_SEARCH'),
('show me items branded Ruhuka', 'PRODUCT_SEARCH'),
('search for products in the sanitary category', 'PRODUCT_SEARCH'),
('what do we sell in the fasteners category', 'PRODUCT_SEARCH'),
('show me all cement products low on stock in Kigali', 'LOW_STOCK_SEARCH'),
('what products are running low', 'LOW_STOCK_SEARCH'),
('which items need to be reordered', 'LOW_STOCK_SEARCH'),
('show low stock products in the Kigali warehouse', 'LOW_STOCK_SEARCH'),
('what is running out in Huye warehouse', 'LOW_STOCK_SEARCH'),
('list products below reorder level', 'LOW_STOCK_SEARCH'),
('which cement products are low on stock', 'LOW_STOCK_SEARCH'),
('show me items that need restocking', 'LOW_STOCK_SEARCH'),
('what products are almost out of stock', 'LOW_STOCK_SEARCH'),
('which brands are running low', 'LOW_STOCK_SEARCH'),
('show low stock paint products', 'LOW_STOCK_SEARCH'),
('list items low on stock in Musanze', 'LOW_STOCK_SEARCH'),
('what needs reordering in Kigali', 'LOW_STOCK_SEARCH'),
('show me products close to reorder level', 'LOW_STOCK_SEARCH'),
('which steel products are low', 'LOW_STOCK_SEARCH'),
('list all low stock items', 'LOW_STOCK_SEARCH'),
('what is low on stock right now', 'LOW_STOCK_SEARCH'),
('show low stock products from Dangote', 'LOW_STOCK_SEARCH'),
('which products in the roofing category are low', 'LOW_STOCK_SEARCH'),
('what is about to run out in Kigali warehouse', 'LOW_STOCK_SEARCH'),
('show me reorder alerts', 'LOW_STOCK_SEARCH'),
('list products running low on stock', 'LOW_STOCK_SEARCH'),
('which pipes are low in stock', 'LOW_STOCK_SEARCH'),
('show low inventory items', 'LOW_STOCK_SEARCH'),
('what products are below their reorder point', 'LOW_STOCK_SEARCH'),
('list low stock items in the electrical category', 'LOW_STOCK_SEARCH'),
('show me what is low in Huye', 'LOW_STOCK_SEARCH'),
('which tiles are running low', 'LOW_STOCK_SEARCH'),
('what needs restocking soon', 'LOW_STOCK_SEARCH'),
('show low stock nails', 'LOW_STOCK_SEARCH');
